version: "3.9"
name: "go-food"
networks:
  go-food:

services:
  app:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    image: go-food-app
    ports:
      - 8080:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    networks:
      - go-food

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=go_food
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - 5432:5432
    networks:
      - go-food
